# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-11 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='update',
            old_name='images',
            new_name='image',
        ),
    ]
