# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-18 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import status.models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20180718_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=status.models.upload_status_image),
        ),
    ]
